---
#######################
# Default base values #
#######################

# Disable unnecessary components
components:
  # zookeeper
  # zookeeper: true
  # bookkeeper
  # bookkeeper: true
  # bookkeeper - autorecovery
  # autorecovery: true
  # broker
  # broker: true
  # functions
  functions: false
  # proxy
  proxy: false
  # toolset
  toolset: false
  # pulsar manager
  pulsar_manager: false

# Disable monitoring stack workloads
victoria-metrics-k8s-stack:
  enabled: false
  victoria-metrics-operator:
    enabled: false
  vmsingle:
    enabled: false
  vmagent:
    enabled: false
  kube-state-metrics:
    enabled: false
  prometheus-node-exporter:
    enabled: false
  grafana:
    enabled: false

# Disable monitoring scrapers (*.podMonitors)
# Use private GCP components (*.service.annotations)
# Use SSDs for persistence (*.volumes.data.storageClassName)
# Modify requests for anti-affinity pods for GKE Autopilot General-purpose compute class (*.resources.requests)
autorecovery:
  podMonitor:
    enabled: false
  service:
    annotations:
      networking.gke.io/load-balancer-type: "Internal"
  volumes:
    data:
      storageClassName: premium-rwo
  affinity:
    anti_affinity: true # Documentative explicit default
  resources:
    requests:
      cpu: 0.5 # Default: 0.05
bookkeeper:
  podMonitor:
    enabled: false
  service:
    annotations:
      networking.gke.io/load-balancer-type: "Internal"
  volumes:
    data:
      storageClassName: premium-rwo
  affinity:
    anti_affinity: true # Documentative explicit default
  resources:
    requests:
      cpu: 0.5 # Default: 0.2
# Oxia server requests are high enough by default (1/1Gi), coordinator is not anti-affinity.
oxia:
  server:
    podMonitor:
      enabled: false
    service:
      annotations:
        networking.gke.io/load-balancer-type: "Internal"
    volumes:
      data:
        storageClassName: premium-rwo
  coordinator:
    podMonitor:
      enabled: false
    service:
      annotations:
        networking.gke.io/load-balancer-type: "Internal"
    volumes:
      data:
        storageClassName: premium-rwo
# Broker requests are adjusted high enough by Autopilot by default
broker:
  podMonitor:
    enabled: false
  service:
    annotations:
      networking.gke.io/load-balancer-type: "Internal"
  volumes:
    data:
      storageClassName: premium-rwo
# (Proxy is a disabled component)
proxy:
  podMonitor:
    enabled: false
  service:
    annotations:
      networking.gke.io/load-balancer-type: "Internal"
  volumes:
    data:
      storageClassName: premium-rwo
zookeeper:
  podMonitor:
    enabled: false
  service:
    annotations:
      networking.gke.io/load-balancer-type: "Internal"
  volumes:
    data:
      storageClassName: premium-rwo
  affinity:
    anti_affinity: true # Documentative explicit default
  resources:
    requests:
      cpu: 0.5 # Default: 0.1
