---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- ../../base
# Because generators cannot be patched, they are duplicated
generators:
- ./apache-pulsar-helm-generator.yaml
