apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: mqtt-pulsar-forwarder-qa
  namespace: argocd
  annotations:
    argocd-image-updater.argoproj.io/write-back-method: argocd
    argocd-image-updater.argoproj.io/image-list:  myalias=tvvlmj/mqtt-pulsar-forwarder:edge
    argocd-image-updater.argoproj.io/update-strategy: digest
spec:
  project: waltti
  source:
    repoURL: https://github.com/tvv-lippu-ja-maksujarjestelma-oy/waltti-apc-deployment.git
    path: manifests/mqtt-pulsar-forwarder/overlays/qa
  destination:
    server: https://34.159.35.141
  syncPolicy:  
    automated: 
      prune: true
      selfheal: true