apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: http-pulsar-poller-jyvaskyla
  namespace: argocd
spec:
  project: waltti
  source:
    repoURL: https://github.com/tvv-lippu-ja-maksujarjestelma-oy/waltti-apc-deployment.git
    path: manifests/http-pulsar-poller/jyvaskyla/overlays/dev
  destination:
    server: https://kubernetes.default.svc
  syncPolicy:  
    automated: {}