apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: vehicle-anonymization-profiler-qa
  namespace: argocd
  labels:
    environment: qa
    name: vehicle-anonymization-profiler-qa
  annotations:
    argocd-image-updater.argoproj.io/write-back-method: argocd
    argocd-image-updater.argoproj.io/image-list: tvvlmj/waltti-apc-vehicle-anonymization-profiler:edge
    argocd-image-updater.argoproj.io/update-strategy: digest
spec:
  project: waltti
  source:
    repoURL: https://github.com/tvv-lippu-ja-maksujarjestelma-oy/waltti-apc-deployment.git
    path: manifests/vehicle-anonymization-profiler/overlays/staging
  destination:
    server: https://kubernetes.default.svc
  syncPolicy:  
    automated: 
      prune: true