apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: mqtt-pulsar-forwarder-dev
  namespace: argocd
  labels:
    environment: dev
    name: mqtt-pulsar-forwarder
  annotations:
    argocd-image-updater.argoproj.io/write-back-method: argocd
    argocd-image-updater.argoproj.io/image-list: tvvlmj/mqtt-pulsar-forwarder:edge
    argocd-image-updater.argoproj.io/update-strategy: digest
spec:
  project: waltti
  source:
    repoURL: https://github.com/tvv-lippu-ja-maksujarjestelma-oy/waltti-apc-deployment.git
    path: manifests/mqtt-pulsar-forwarder/overlays/dev
  destination:
    server: https://kubernetes.default.svc
  syncPolicy:  
    automated: 
      prune: true