apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: pulsar-mqtt-forwarder-raportointi
  namespace: argocd
  labels:
    environment: dev
    name: pulsar-mqtt-forwarder-raportointi
  annotations:
    argocd-image-updater.argoproj.io/write-back-method: argocd
    argocd-image-updater.argoproj.io/image-list: tvvlmj/pulsar-mqtt-forwarder:edge
    argocd-image-updater.argoproj.io/update-strategy: digest
spec:
  project: waltti
  source:
    repoURL: https://github.com/tvv-lippu-ja-maksujarjestelma-oy/waltti-apc-deployment.git
    path: manifests/pulsar-mqtt-forwarder/raportointi/overlays/dev
  destination:
    server: https://kubernetes.default.svc
  syncPolicy:  
    automated: 
      prune: true
      selfHeal: true