apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: journey-matcher
  namespace: argocd
spec:
  project: waltti
  source:
    repoURL: https://github.com/tvv-lippu-ja-maksujarjestelma-oy/waltti-apc-deployment.git
    path: manifests/journey-matcher/overlays/dev
  destination:
    server: https://kubernetes.default.svc
