apiVersion: v1
kind: ConfigMap
metadata:
  name: argocd-cm
data:
  # Needed for the KSOPS exec plugin.
  kustomize.buildOptions: --enable-alpha-plugins --enable-exec
  resource.exclusions: |
    - apiGroups:
      - cilium.io
      kinds:
      - CiliumIdentity
      clusters:
      - "*"
