name: "Terraform CI"

on:
  push:
    branches:
    # DISABLE THIS for now, should be main
      - "dev"

jobs:
  terraform:
    permissions:
      contents: "read"
      id-token: "write"
      pull-requests: "write"
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./environments/dev
    steps:
    - uses: actions/checkout@v3

    - id: "auth"
      name: "Authenticate to Google Cloud"
      uses: google-github-actions/auth@v1
      with:
        workload_identity_provider: ${{ secrets.workload_id_pool }}
        service_account: ${{ secrets.tf_service_account }}
        token_format: 'access_token'

    - uses: hashicorp/setup-terraform@v2
      with:
        terraform_version: 1.4.0

    - name: Terraform fmt
      id: fmt
      run: terraform fmt -check
      continue-on-error: true

    - name: Terraform Init
      id: init
      run: terraform init
      env: 
        TF_VAR_project_id: ${{ secrets.project_id }}
        TF_VAR_environment: "sandbox"
        TF_VAR_tf_service_account: ${{ secrets.tf_service_account }}

    - name: Terraform Validate
      id: validate
      run: terraform validate -no-color

    # FIXME: timesout!
    # - name: Terraform Plan
    #   id: plan
    #   run: terraform plan -no-color
    #   continue-on-error: false
